# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ring": "00_graph_functions.ipynb",
         "table": "00_graph_functions.ipynb",
         "print_graph": "00_graph_functions.ipynb",
         "parse_kwargs": "00_graph_functions.ipynb",
         "give_nodes": "00_graph_functions.ipynb",
         "parse_edges": "00_graph_functions.ipynb",
         "give_edges": "00_graph_functions.ipynb",
         "node_attrs": "00_graph_functions.ipynb",
         "edge_attrs": "00_graph_functions.ipynb",
         "node_data": "00_graph_functions.ipynb",
         "edge_data": "00_graph_functions.ipynb",
         "argwhere": "00_graph_functions.ipynb",
         "kwargwhere": "00_graph_functions.ipynb",
         "where": "00_graph_functions.ipynb",
         "parse_lengths": "00_graph_functions.ipynb",
         "convert_edges": "00_graph_functions.ipynb",
         "relabel_graph": "00_graph_functions.ipynb",
         "sort_graph": "00_graph_functions.ipynb",
         "sigmoid": "01_model_functions.ipynb",
         "graph_iter": "01_model_functions.ipynb",
         "dde_derivative": "01_model_functions.ipynb",
         "dde_derivative_risefall": "01_model_functions.ipynb",
         "dde_integrator": "01_model_functions.ipynb",
         "parse_initial_conditions": "01_model_functions.ipynb",
         "plot_graph": "01_model_functions.ipynb",
         "graph_model": "01_model_functions.ipynb",
         "Network": "02_network_class.ipynb"}

modules = ["graph_functions.py",
           "model_functions.py",
           "network_class.py"]

doc_url = "https://Noeloikeau.github.io/networkm/"

git_url = "https://github.com/Noeloikeau/networkm/tree/master/"

def custom_doc_links(name): return None
