# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ring": "00_network.ipynb",
         "adj": "00_network.ipynb",
         "table": "00_network.ipynb",
         "print_graph": "00_network.ipynb",
         "parse_kwargs": "00_network.ipynb",
         "give_nodes": "00_network.ipynb",
         "parse_edges": "00_network.ipynb",
         "give_edges": "00_network.ipynb",
         "node_attrs": "00_network.ipynb",
         "edge_attrs": "00_network.ipynb",
         "node_data": "00_network.ipynb",
         "edge_data": "00_network.ipynb",
         "argwhere": "00_network.ipynb",
         "kwargwhere": "00_network.ipynb",
         "where": "00_network.ipynb",
         "parse_lengths": "00_network.ipynb",
         "edge_to_line": "00_network.ipynb",
         "edge_to_tree": "00_network.ipynb",
         "convert_edges_to_paths": "00_network.ipynb",
         "convert_paths_to_edges": "00_network.ipynb",
         "add_star": "00_network.ipynb",
         "relabel_graph": "00_network.ipynb",
         "sort_graph": "00_network.ipynb",
         "Network": "00_network.ipynb",
         "NetworkModel": "01_models.ipynb",
         "dde_iter": "01_models.ipynb"}

modules = ["network.py",
           "models.py"]

doc_url = "https://Noeloikeau.github.io/networkm/"

git_url = "https://github.com/Noeloikeau/networkm/tree/master/"

def custom_doc_links(name): return None
